name: tool_stable_diffusion_api
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda=11.7.1=0
  - cuda-cccl=11.7.91=0
  - cuda-command-line-tools=11.7.1=0
  - cuda-compiler=11.7.1=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cuobjdump=11.7.91=0
  - cuda-cupti=11.7.101=0
  - cuda-cuxxfilt=11.7.91=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.7.99=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.7.91=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.7.91=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.7.1=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=11.7.1=0
  - cuda-visual-tools=11.7.1=0
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17
  - libffi=3.4.2
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nsight-compute=2023.1.0.15
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0=cuda
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - redis==4.5.3
      - accelerate==0.16.0
      - anyio==3.6.2
      - click==8.1.3
      - colorama==0.4.6
      - diffusers==0.13.1
      - fastapi==0.92.0
      - filelock==3.9.0
      - ftfy==6.1.1
      - h11==0.14.0
      - huggingface-hub==0.12.1
      - importlib-metadata==6.0.0
      - packaging==23.0
      - psutil==5.9.4
      - pydantic==1.10.5
      - pyjwt==2.6.0
      - pyyaml==6.0
      - regex==2022.10.31
      - scipy==1.10.1
      - sniffio==1.3.0
      - starlette==0.25.0
      - tokenizers==0.13.2
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.65.0
      - transformers==4.26.1
      - uvicorn==0.20.0
      - wcwidth==0.2.6
      - zipp==3.15.0
      - numpy
